/**
 * Слова та сталі фрази (іспанська → українська).
 * Якщо у фрази є пробіли — у картці покажеться мітка «Фраза»; для одного слова — «Слово».
 * Можна задати tag: "word" | "phrase", щоб перевизначити.
 */
export const DUMOSVIT_VOCAB = [
  // ——— Базові привітання й ввічливість ———
  { es: "hola", uk: "привіт" },
  { es: "gracias", uk: "дякую" },
  { es: "por favor", uk: "будь ласка" },
  { es: "sí", uk: "так" },
  { es: "no", uk: "ні" },
  { es: "buenos días", uk: "доброго ранку" },
  { es: "buenas tardes", uk: "добрий день (після обіду)" },
  { es: "buenas noches", uk: "добраніч / добрий вечір" },
  { es: "adiós", uk: "бувай" },
  { es: "perdón", uk: "вибач(те)" },
  { es: "de nada", uk: "нема за що" },
  { es: "muchas gracias", uk: "велике дякую" },
  { es: "con permiso", uk: "дозвольте (пройти)" },
  { es: "disculpe", uk: "вибачте (привернути увагу)" },
  { es: "encantado de conocerte", uk: "приємно познайомитися (чол.)" },
  { es: "encantada de conocerte", uk: "приємно познайомитися (жін.)" },
  { es: "igualmente", uk: "взаємно" },
  { es: "feliz cumpleaños", uk: "з днем народження" },
  { es: "¡Feliz Año Nuevo!", uk: "з Новим роком!" },
  { es: "salud", uk: "будьмо! / на здоров’я! (після чхання)" },

  // ——— Питання й відповіді в діалозі ———
  { es: "¿Cómo estás?", uk: "як справи? (на ти)" },
  { es: "¿Cómo está usted?", uk: "як справи? (на Ви)" },
  { es: "Muy bien, gracias", uk: "дуже добре, дякую" },
  { es: "¿Qué tal?", uk: "як життя? / як справи?" },
  { es: "¿De dónde eres?", uk: "звідки ти?" },
  { es: "Soy de Ucrania", uk: "я з України" },
  { es: "Me llamo…", uk: "мене звати…" },
  { es: "¿Cuántos años tienes?", uk: "скільки тобі років?" },
  { es: "No entiendo", uk: "я не розумію" },
  { es: "No sé", uk: "я не знаю" },
  { es: "¿Puede repetir, por favor?", uk: "повторіть, будь ласка?" },
  { es: "¿Habla inglés?", uk: "ви говорите англійською?" },
  { es: "Hablo un poco de español", uk: "я трохи говорю іспанською" },
  { es: "¿Qué significa esto?", uk: "що це означає?" },
  { es: "Más despacio, por favor", uk: "повільніше, будь ласка" },

  // ——— У кафе, магазині, на вулиці ———
  { es: "Un café, por favor", uk: "каву, будь ласка" },
  { es: "La cuenta, por favor", uk: "рахунок, будь ласка" },
  { es: "¿Cuánto cuesta?", uk: "скільки коштує?" },
  { es: "Es caro", uk: "це дорого" },
  { es: "Es barato", uk: "це дешево" },
  { es: "¿Dónde está el baño?", uk: "де туалет?" },
  { es: "¿Dónde hay un cajero?", uk: "де є банкомат?" },
  { es: "Estoy perdido", uk: "я заблукав (чол.)" },
  { es: "Estoy perdida", uk: "я заблукала (жін.)" },
  { es: "¡Que aproveche!", uk: "смачного! (коли хтось їсть)" },
  { es: "Tengo hambre", uk: "я голодний" },
  { es: "Tengo sed", uk: "мене мучить спрага" },
  { es: "Necesito ayuda", uk: "мені потрібна допомога" },

  // ——— Прощання ———
  { es: "hasta luego", uk: "до побачення (незабаром)" },
  { es: "hasta mañana", uk: "до завтра" },
  { es: "nos vemos", uk: "побачимось" },
  { es: "cuídate", uk: "бережи себе (на ти)" },
  { es: "¡Que tengas un buen día!", uk: "гарного дня!" },

  // ——— Час і місце ———
  { es: "ahora", uk: "зараз" },
  { es: "hoy", uk: "сьогодні" },
  { es: "ayer", uk: "вчора" },
  { es: "mañana", uk: "завтра / ранок" },
  { es: "siempre", uk: "завжди" },
  { es: "nunca", uk: "ніколи" },
  { es: "a veces", uk: "іноді" },
  { es: "aquí", uk: "тут" },
  { es: "allí", uk: "там" },
  { es: "lejos", uk: "далеко" },
  { es: "cerca", uk: "близько" },
  { es: "día", uk: "день" },
  { es: "noche", uk: "ніч" },
  { es: "semana", uk: "тиждень" },
  { es: "mes", uk: "місяць" },
  { es: "año", uk: "рік" },
  { es: "lunes", uk: "понеділок" },
  { es: "martes", uk: "вівторок" },
  { es: "miércoles", uk: "середа" },
  { es: "jueves", uk: "четвер" },
  { es: "viernes", uk: "п’ятниця" },
  { es: "sábado", uk: "субота" },
  { es: "domingo", uk: "неділя" },

  // ——— Речі навколо ———
  { es: "agua", uk: "вода" },
  { es: "comida", uk: "їжа" },
  { es: "casa", uk: "дім" },
  { es: "puerta", uk: "двері" },
  { es: "ventana", uk: "вікно" },
  { es: "mesa", uk: "стіл" },
  { es: "silla", uk: "стілець" },
  { es: "cama", uk: "ліжко" },
  { es: "libro", uk: "книга" },
  { es: "teléfono", uk: "телефон" },
  { es: "coche", uk: "авто (іспанською Європи)" },
  { es: "ciudad", uk: "місто" },
  { es: "país", uk: "країна" },
  { es: "lugar", uk: "місце" },
  { es: "calle", uk: "вулиця" },
  { es: "dinero", uk: "гроші" },
  { es: "trabajo", uk: "робота" },
  { es: "tiempo", uk: "час / погода" },
  { es: "música", uk: "музика" },
  { es: "película", uk: "фільм" },

  // ——— Люди й тіло ———
  { es: "familia", uk: "родина" },
  { es: "amigo", uk: "друг" },
  { es: "amiga", uk: "подруга" },
  { es: "padre", uk: "батько" },
  { es: "madre", uk: "мати" },
  { es: "hermano", uk: "брат" },
  { es: "hermana", uk: "сестра" },
  { es: "hijo", uk: "син" },
  { es: "hija", uk: "дочка" },
  { es: "persona", uk: "людина" },
  { es: "mano", uk: "рука" },
  { es: "cabeza", uk: "голова" },
  { es: "corazón", uk: "серце" },
  { es: "ojos", uk: "очі" },

  // ——— Прикметники й кількість ———
  { es: "grande", uk: "великий" },
  { es: "pequeño", uk: "маленький" },
  { es: "nuevo", uk: "новий" },
  { es: "viejo", uk: "старий" },
  { es: "bueno", uk: "добрий" },
  { es: "malo", uk: "поганий" },
  { es: "muy", uk: "дуже" },
  { es: "bien", uk: "добре" },
  { es: "mal", uk: "погано" },
  { es: "mucho", uk: "багато" },
  { es: "poco", uk: "мало" },
  { es: "todo", uk: "усе / увесь" },
  { es: "nada", uk: "нічого" },
  { es: "algo", uk: "щось" },
  { es: "alguien", uk: "хтось" },
  { es: "uno", uk: "один" },
  { es: "dos", uk: "два" },
  { es: "tres", uk: "три" },
  { es: "cuatro", uk: "чотири" },
  { es: "cinco", uk: "п’ять" },
  { es: "rojo", uk: "червоний" },
  { es: "azul", uk: "синій" },
  { es: "verde", uk: "зелений" },
  { es: "blanco", uk: "білий" },
  { es: "negro", uk: "чорний" },

  // ——— Погода ———
  { es: "sol", uk: "сонце" },
  { es: "lluvia", uk: "дощ" },
  { es: "frío", uk: "холод" },
  { es: "calor", uk: "спека" },
  { es: "Hace buen tiempo", uk: "гарна погода" },
  { es: "Hace mal tiempo", uk: "погана погода" },

  // ——— Їжа ———
  { es: "pan", uk: "хліб" },
  { es: "leche", uk: "молоко" },
  { es: "café", uk: "кава" },
  { es: "té", uk: "чай" },
  { es: "carne", uk: "м’ясо" },
  { es: "pescado", uk: "риба (як страва)" },
  { es: "fruta", uk: "фрукт" },
  { es: "verdura", uk: "овоч" },
  { es: "huevo", uk: "яйце" },
  { es: "queso", uk: "сир" },

  // ——— Дієслова (інфінітиви) ———
  { es: "ser", uk: "бути (про сутність)" },
  { es: "estar", uk: "бути (про стан / місце)" },
  { es: "tener", uk: "мати" },
  { es: "haber", uk: "бути (допоміжне) / є" },
  { es: "hacer", uk: "робити / робити (дія)" },
  { es: "ir", uk: "йти / їхати" },
  { es: "venir", uk: "приходити" },
  { es: "ver", uk: "бачити" },
  { es: "saber", uk: "знати (факти)" },
  { es: "conocer", uk: "знати (людей / місця)" },
  { es: "poder", uk: "могти" },
  { es: "querer", uk: "хотіти / любити" },
  { es: "deber", uk: "повинен / варто" },
  { es: "necesitar", uk: "потребувати" },
  { es: "gustar", uk: "подобатися" },
  { es: "hablar", uk: "говорити" },
  { es: "entender", uk: "розуміти" },
  { es: "decir", uk: "казати" },
  { es: "dar", uk: "давати" },
  { es: "comer", uk: "їсти" },
  { es: "beber", uk: "пити" },
  { es: "dormir", uk: "спати" },
  { es: "vivir", uk: "жити" },
  { es: "estudiar", uk: "вчитися" },
  { es: "trabajar", uk: "працювати" },
  { es: "comprar", uk: "купувати" },
  { es: "vender", uk: "продавати" },
  { es: "ayudar", uk: "допомагати" },
  { es: "esperar", uk: "чекати / сподіватися" },
  { es: "llamar", uk: "звати / дзвонити" },

  // ——— Сполучники й питальні ———
  { es: "y", uk: "і" },
  { es: "o", uk: "або" },
  { es: "pero", uk: "але" },
  { es: "porque", uk: "тому що" },
  { es: "también", uk: "також" },
  { es: "qué", uk: "що" },
  { es: "quién", uk: "хто" },
  { es: "dónde", uk: "де" },
  { es: "cuándo", uk: "коли" },
  { es: "cómo", uk: "як" },
  { es: "cuánto", uk: "скільки" },
  { es: "por qué", uk: "чому" },

  // ——— Навчання й місто ———
  { es: "escuela", uk: "школа" },
  { es: "universidad", uk: "університет" },
  { es: "hospital", uk: "лікарня" },
  { es: "farmacia", uk: "аптека" },
  { es: "hotel", uk: "готель" },
  { es: "aeropuerto", uk: "аеропорт" },
  { es: "estación", uk: "вокзал / станція" },
  { es: "ayuda", uk: "допомога" },
  { es: "problema", uk: "проблема" },
  { es: "solución", uk: "рішення" },
];

/** @deprecated використовуй DUMOSVIT_VOCAB; залишено для сумісності */
export const DUMOSVIT_WORDS = DUMOSVIT_VOCAB;
