/**
 * Слова та сталі фрази (іспанська → українська).
 * Якщо у фрази є пробіли — у картці покажеться мітка «Фраза»; для одного слова — «Слово».
 * Можна задати tag: "word" | "phrase", щоб перевизначити.
 */
export const DUMOSVIT_VOCAB = [
  // ——— Базові привітання й ввічливість ———
  { es: "hola", uk: "привіт" },
  { es: "gracias", uk: "дякую" },
  { es: "por favor", uk: "будь ласка" },
  { es: "sí", uk: "так" },
  { es: "no", uk: "ні" },
  { es: "buenos días", uk: "доброго ранку" },
  { es: "buenas tardes", uk: "добрий день (після обіду)" },
  { es: "buenas noches", uk: "добраніч / добрий вечір" },
  { es: "adiós", uk: "бувай" },
  { es: "perdón", uk: "вибач(те)" },
  { es: "de nada", uk: "нема за що" },
  { es: "muchas gracias", uk: "велике дякую" },
  { es: "con permiso", uk: "дозвольте (пройти)" },
  { es: "disculpe", uk: "вибачте (привернути увагу)" },
  { es: "encantado de conocerte", uk: "приємно познайомитися (чол.)" },
  { es: "encantada de conocerte", uk: "приємно познайомитися (жін.)" },
  { es: "igualmente", uk: "взаємно" },
  { es: "feliz cumpleaños", uk: "з днем народження" },
  { es: "¡Feliz Año Nuevo!", uk: "з Новим роком!" },
  { es: "salud", uk: "будьмо! / на здоров’я! (після чхання)" },

  // ——— Питання й відповіді в діалозі ———
  { es: "¿Cómo estás?", uk: "як справи? (на ти)" },
  { es: "¿Cómo está usted?", uk: "як справи? (на Ви)" },
  { es: "Muy bien, gracias", uk: "дуже добре, дякую" },
  { es: "¿Qué tal?", uk: "як життя? / як справи?" },
  { es: "¿De dónde eres?", uk: "звідки ти?" },
  { es: "Soy de Ucrania", uk: "я з України" },
  { es: "Me llamo…", uk: "мене звати…" },
  { es: "¿Cuántos años tienes?", uk: "скільки тобі років?" },
  { es: "No entiendo", uk: "я не розумію" },
  { es: "No sé", uk: "я не знаю" },
  { es: "¿Puede repetir, por favor?", uk: "повторіть, будь ласка?" },
  { es: "¿Habla inglés?", uk: "ви говорите англійською?" },
  { es: "Hablo un poco de español", uk: "я трохи говорю іспанською" },
  { es: "¿Qué significa esto?", uk: "що це означає?" },
  { es: "Más despacio, por favor", uk: "повільніше, будь ласка" },

  // ——— У кафе, магазині, на вулиці ———
  { es: "Un café, por favor", uk: "каву, будь ласка" },
  { es: "La cuenta, por favor", uk: "рахунок, будь ласка" },
  { es: "¿Cuánto cuesta?", uk: "скільки коштує?" },
  { es: "Es caro", uk: "це дорого" },
  { es: "Es barato", uk: "це дешево" },
  { es: "¿Dónde está el baño?", uk: "де туалет?" },
  { es: "¿Dónde hay un cajero?", uk: "де є банкомат?" },
  { es: "Estoy perdido", uk: "я заблукав (чол.)" },
  { es: "Estoy perdida", uk: "я заблукала (жін.)" },
  { es: "¡Que aproveche!", uk: "смачного! (коли хтось їсть)" },
  { es: "Tengo hambre", uk: "я голодний" },
  { es: "Tengo sed", uk: "мене мучить спрага" },
  { es: "Necesito ayuda", uk: "мені потрібна допомога" },

  // ——— Прощання ———
  { es: "hasta luego", uk: "до побачення (незабаром)" },
  { es: "hasta mañana", uk: "до завтра" },
  { es: "nos vemos", uk: "побачимось" },
  { es: "cuídate", uk: "бережи себе (на ти)" },
  { es: "¡Que tengas un buen día!", uk: "гарного дня!" },

  // ——— Час і місце ———
  { es: "ahora", uk: "зараз" },
  { es: "hoy", uk: "сьогодні" },
  { es: "ayer", uk: "вчора" },
  { es: "mañana", uk: "завтра / ранок" },
  { es: "siempre", uk: "завжди" },
  { es: "nunca", uk: "ніколи" },
  { es: "a veces", uk: "іноді" },
  { es: "aquí", uk: "тут" },
  { es: "allí", uk: "там" },
  { es: "lejos", uk: "далеко" },
  { es: "cerca", uk: "близько" },
  { es: "día", uk: "день" },
  { es: "noche", uk: "ніч" },
  { es: "semana", uk: "тиждень" },
  { es: "mes", uk: "місяць" },
  { es: "año", uk: "рік" },
  { es: "lunes", uk: "понеділок" },
  { es: "martes", uk: "вівторок" },
  { es: "miércoles", uk: "середа" },
  { es: "jueves", uk: "четвер" },
  { es: "viernes", uk: "п’ятниця" },
  { es: "sábado", uk: "субота" },
  { es: "domingo", uk: "неділя" },

  // ——— Речі навколо ———
  { es: "agua", uk: "вода" },
  { es: "comida", uk: "їжа" },
  { es: "casa", uk: "дім" },
  { es: "puerta", uk: "двері" },
  { es: "ventana", uk: "вікно" },
  { es: "mesa", uk: "стіл" },
  { es: "silla", uk: "стілець" },
  { es: "cama", uk: "ліжко" },
  { es: "libro", uk: "книга" },
  { es: "teléfono", uk: "телефон" },
  { es: "coche", uk: "авто (іспанською Європи)" },
  { es: "ciudad", uk: "місто" },
  { es: "país", uk: "країна" },
  { es: "lugar", uk: "місце" },
  { es: "calle", uk: "вулиця" },
  { es: "dinero", uk: "гроші" },
  { es: "trabajo", uk: "робота" },
  { es: "tiempo", uk: "час / погода" },
  { es: "música", uk: "музика" },
  { es: "película", uk: "фільм" },

  // ——— Люди й тіло ———
  { es: "familia", uk: "родина" },
  { es: "amigo", uk: "друг" },
  { es: "amiga", uk: "подруга" },
  { es: "padre", uk: "батько" },
  { es: "madre", uk: "мати" },
  { es: "hermano", uk: "брат" },
  { es: "hermana", uk: "сестра" },
  { es: "hijo", uk: "син" },
  { es: "hija", uk: "дочка" },
  { es: "persona", uk: "людина" },
  { es: "mano", uk: "рука" },
  { es: "cabeza", uk: "голова" },
  { es: "corazón", uk: "серце" },
  { es: "ojos", uk: "очі" },

  // ——— Прикметники й кількість ———
  { es: "grande", uk: "великий" },
  { es: "pequeño", uk: "маленький" },
  { es: "nuevo", uk: "новий" },
  { es: "viejo", uk: "старий" },
  { es: "bueno", uk: "добрий" },
  { es: "malo", uk: "поганий" },
  { es: "muy", uk: "дуже" },
  { es: "bien", uk: "добре" },
  { es: "mal", uk: "погано" },
  { es: "mucho", uk: "багато" },
  { es: "poco", uk: "мало" },
  { es: "todo", uk: "усе / увесь" },
  { es: "nada", uk: "нічого" },
  { es: "algo", uk: "щось" },
  { es: "alguien", uk: "хтось" },
  { es: "uno", uk: "один" },
  { es: "dos", uk: "два" },
  { es: "tres", uk: "три" },
  { es: "cuatro", uk: "чотири" },
  { es: "cinco", uk: "п’ять" },
  { es: "rojo", uk: "червоний" },
  { es: "azul", uk: "синій" },
  { es: "verde", uk: "зелений" },
  { es: "blanco", uk: "білий" },
  { es: "negro", uk: "чорний" },

  // ——— Погода ———
  { es: "sol", uk: "сонце" },
  { es: "lluvia", uk: "дощ" },
  { es: "frío", uk: "холод" },
  { es: "calor", uk: "спека" },
  { es: "Hace buen tiempo", uk: "гарна погода" },
  { es: "Hace mal tiempo", uk: "погана погода" },

  // ——— Їжа ———
  { es: "pan", uk: "хліб" },
  { es: "leche", uk: "молоко" },
  { es: "café", uk: "кава" },
  { es: "té", uk: "чай" },
  { es: "carne", uk: "м’ясо" },
  { es: "pescado", uk: "риба (як страва)" },
  { es: "fruta", uk: "фрукт" },
  { es: "verdura", uk: "овоч" },
  { es: "huevo", uk: "яйце" },
  { es: "queso", uk: "сир" },

  // ——— Дієслова (інфінітиви) ———
  { es: "ser", uk: "бути (про сутність)" },
  { es: "estar", uk: "бути (про стан / місце)" },
  { es: "tener", uk: "мати" },
  { es: "haber", uk: "бути (допоміжне) / є" },
  { es: "hacer", uk: "робити / робити (дія)" },
  { es: "ir", uk: "йти / їхати" },
  { es: "venir", uk: "приходити" },
  { es: "ver", uk: "бачити" },
  { es: "saber", uk: "знати (факти)" },
  { es: "conocer", uk: "знати (людей / місця)" },
  { es: "poder", uk: "могти" },
  { es: "querer", uk: "хотіти / любити" },
  { es: "deber", uk: "повинен / варто" },
  { es: "necesitar", uk: "потребувати" },
  { es: "gustar", uk: "подобатися" },
  { es: "hablar", uk: "говорити" },
  { es: "entender", uk: "розуміти" },
  { es: "decir", uk: "казати" },
  { es: "dar", uk: "давати" },
  { es: "comer", uk: "їсти" },
  { es: "beber", uk: "пити" },
  { es: "dormir", uk: "спати" },
  { es: "vivir", uk: "жити" },
  { es: "estudiar", uk: "вчитися" },
  { es: "trabajar", uk: "працювати" },
  { es: "comprar", uk: "купувати" },
  { es: "vender", uk: "продавати" },
  { es: "ayudar", uk: "допомагати" },
  { es: "esperar", uk: "чекати / сподіватися" },
  { es: "llamar", uk: "звати / дзвонити" },

  // ——— Сполучники й питальні ———
  { es: "y", uk: "і" },
  { es: "o", uk: "або" },
  { es: "pero", uk: "але" },
  { es: "porque", uk: "тому що" },
  { es: "también", uk: "також" },
  { es: "qué", uk: "що" },
  { es: "quién", uk: "хто" },
  { es: "dónde", uk: "де" },
  { es: "cuándo", uk: "коли" },
  { es: "cómo", uk: "як" },
  { es: "cuánto", uk: "скільки" },
  { es: "por qué", uk: "чому" },

  // ——— Навчання й місто ———
  { es: "escuela", uk: "школа" },
  { es: "universidad", uk: "університет" },
  { es: "hospital", uk: "лікарня" },
  { es: "farmacia", uk: "аптека" },
  { es: "hotel", uk: "готель" },
  { es: "aeropuerto", uk: "аеропорт" },
  { es: "estación", uk: "вокзал / станція" },
  { es: "ayuda", uk: "допомога" },
  { es: "problema", uk: "проблема" },
  { es: "solución", uk: "рішення" },

  // ——— Дні тижня й час ———
  { es: "fin de semana", uk: "вихідні" },
  { es: "pasado mañana", uk: "післязавтра" },
  { es: "anteayer", uk: "позавчора" },
  { es: "hora", uk: "година" },
  { es: "minuto", uk: "хвилина" },
  { es: "temprano", uk: "рано" },
  { es: "tarde", uk: "пізно / вечір (після обіду)" },
  { es: "todavía", uk: "ще / досі" },
  { es: "ya", uk: "вже" },
  { es: "¿Qué hora es?", uk: "котра година?" },
  { es: "Son las tres", uk: "зараз третя година" },
  { es: "Es la una y media", uk: "пів на другу" },

  // ——— Місяці й пори року ———
  { es: "enero", uk: "січень" },
  { es: "febrero", uk: "лютий" },
  { es: "marzo", uk: "березень" },
  { es: "abril", uk: "квітень" },
  { es: "mayo", uk: "травень" },
  { es: "junio", uk: "червень" },
  { es: "julio", uk: "липень" },
  { es: "agosto", uk: "серпень" },
  { es: "septiembre", uk: "вересень" },
  { es: "octubre", uk: "жовтень" },
  { es: "noviembre", uk: "листопад" },
  { es: "diciembre", uk: "грудень" },
  { es: "primavera", uk: "весна" },
  { es: "verano", uk: "літо" },
  { es: "otoño", uk: "осінь" },
  { es: "invierno", uk: "зима" },

  // ——— Погода ———
  { es: "Hace calor", uk: "спекотно" },
  { es: "Hace frío", uk: "холодно" },
  { es: "Hace sol", uk: "сонячно" },
  { es: "Está lloviendo", uk: "йде дощ" },
  { es: "Está nevando", uk: "йде сніг" },
  { es: "nube", uk: "хмара" },
  { es: "viento", uk: "вітер" },
  { es: "tormenta", uk: "гроза / шторм" },
  { es: "paraguas", uk: "парасолька" },

  // ——— Сім’я й люди ———
  { es: "abuelo", uk: "дідусь" },
  { es: "abuela", uk: "бабуся" },
  { es: "esposo", uk: "чоловік (у подружжі)" },
  { es: "esposa", uk: "дружина" },
  { es: "novio", uk: "хлопець / наречений" },
  { es: "novia", uk: "дівчина / наречена" },
  { es: "vecino", uk: "сусід" },
  { es: "niño", uk: "дитина / хлопчик" },
  { es: "gente", uk: "люди" },

  // ——— Тіло й здоров’я ———
  { es: "pie", uk: "стопа" },
  { es: "ojo", uk: "око" },
  { es: "boca", uk: "рот" },
  { es: "espalda", uk: "спина" },
  { es: "Me duele la cabeza", uk: "у мене болить голова" },
  { es: "Estoy enfermo", uk: "я хворий" },
  { es: "Estoy cansado", uk: "я втомився" },
  { es: "Necesito un médico", uk: "мені потрібен лікар" },
  { es: "medicina", uk: "ліки" },

  // ——— Їжа й напої ———
  { es: "pollo", uk: "курка" },
  { es: "arroz", uk: "рис" },
  { es: "manzana", uk: "яблуко" },
  { es: "naranja", uk: "апельсин" },
  { es: "azúcar", uk: "цукор" },
  { es: "sal", uk: "сіль" },
  { es: "vino", uk: "вино" },
  { es: "cerveza", uk: "пиво" },
  { es: "zumo", uk: "сік" },
  { es: "desayuno", uk: "сніданок" },
  { es: "almuerzo", uk: "обід" },
  { es: "cena", uk: "вечеря" },
  { es: "¿Qué me recomienda?", uk: "що ви порадите?" },
  { es: "Soy vegetariano", uk: "я вегетаріанець" },
  { es: "Está delicioso", uk: "це дуже смачно" },
  { es: "Una mesa para dos, por favor", uk: "столик на двох, будь ласка" },
  { es: "Sin hielo, por favor", uk: "без льоду, будь ласка" },

  // ——— Дім ———
  { es: "cocina", uk: "кухня" },
  { es: "dormitorio", uk: "спальня" },
  { es: "llave", uk: "ключ" },

  // ——— Подорожі й транспорт ———
  { es: "billete", uk: "квиток" },
  { es: "tren", uk: "потяг" },
  { es: "autobús", uk: "автобус" },
  { es: "avión", uk: "літак" },
  { es: "barco", uk: "корабель / човен" },
  { es: "maleta", uk: "валіза" },
  { es: "pasaporte", uk: "паспорт" },
  { es: "playa", uk: "пляж" },
  { es: "mar", uk: "море" },
  { es: "isla", uk: "острів" },
  { es: "montaña", uk: "гора" },
  { es: "río", uk: "річка" },
  { es: "a la derecha", uk: "праворуч" },
  { es: "a la izquierda", uk: "ліворуч" },
  { es: "todo recto", uk: "прямо" },
  { es: "¿Cómo llego al centro?", uk: "як дістатися до центру?" },
  { es: "Un billete de ida y vuelta", uk: "квиток туди й назад" },
  { es: "¿A qué hora sale el tren?", uk: "о котрій відправляється потяг?" },
  { es: "Tengo una reserva", uk: "у мене є бронювання" },

  // ——— Природа й рибалка ———
  { es: "pez", uk: "риба (жива)" },
  { es: "pescar", uk: "рибалити" },
  { es: "caña de pescar", uk: "вудка" },
  { es: "anzuelo", uk: "гачок" },
  { es: "lago", uk: "озеро" },
  { es: "ola", uk: "хвиля" },
  { es: "árbol", uk: "дерево" },
  { es: "flor", uk: "квітка" },
  { es: "piedra", uk: "камінь" },
  { es: "concha", uk: "мушля" },
  { es: "faro", uk: "маяк" },
  { es: "luna", uk: "місяць (на небі)" },
  { es: "estrella", uk: "зірка" },
  { es: "cielo", uk: "небо" },

  // ——— Часті дієслова ———
  { es: "aprender", uk: "вивчати" },
  { es: "leer", uk: "читати" },
  { es: "escribir", uk: "писати" },
  { es: "escuchar", uk: "слухати" },
  { es: "mirar", uk: "дивитися" },
  { es: "buscar", uk: "шукати" },
  { es: "encontrar", uk: "знаходити" },
  { es: "pagar", uk: "платити" },
  { es: "abrir", uk: "відкривати" },
  { es: "cerrar", uk: "закривати" },
  { es: "empezar", uk: "починати" },
  { es: "terminar", uk: "закінчувати" },
  { es: "pensar", uk: "думати" },
  { es: "sentir", uk: "відчувати" },
  { es: "recordar", uk: "пам’ятати" },
  { es: "olvidar", uk: "забувати" },

  // ——— Прикметники ———
  { es: "bonito", uk: "гарний" },
  { es: "feo", uk: "негарний" },
  { es: "fácil", uk: "легкий (простий)" },
  { es: "difícil", uk: "складний" },
  { es: "rápido", uk: "швидкий" },
  { es: "lento", uk: "повільний" },
  { es: "feliz", uk: "щасливий" },
  { es: "triste", uk: "сумний" },
  { es: "cansado", uk: "втомлений" },
  { es: "listo", uk: "готовий / розумний" },
  { es: "abierto", uk: "відчинений" },
  { es: "cerrado", uk: "зачинений" },
  { es: "lleno", uk: "повний" },
  { es: "vacío", uk: "порожній" },

  // ——— Кольори ———
  { es: "amarillo", uk: "жовтий" },
  { es: "gris", uk: "сірий" },
  { es: "marrón", uk: "коричневий" },

  // ——— Числа ———
  { es: "seis", uk: "шість" },
  { es: "siete", uk: "сім" },
  { es: "ocho", uk: "вісім" },
  { es: "nueve", uk: "дев’ять" },
  { es: "diez", uk: "десять" },
  { es: "veinte", uk: "двадцять" },
  { es: "cien", uk: "сто" },
  { es: "mil", uk: "тисяча" },

  // ——— Емоції й розмовні фрази ———
  { es: "¡Qué bien!", uk: "як класно!" },
  { es: "¡Qué pena!", uk: "як шкода!" },
  { es: "¡Vamos!", uk: "ходімо! / уперед!" },
  { es: "¡Cuidado!", uk: "обережно!" },
  { es: "No pasa nada", uk: "нічого страшного" },
  { es: "Claro", uk: "звісно" },
  { es: "Vale", uk: "гаразд / окей" },
  { es: "Me gusta", uk: "мені подобається" },
  { es: "No me gusta", uk: "мені не подобається" },
  { es: "Te quiero", uk: "я тебе люблю" },
  { es: "Te echo de menos", uk: "я сумую за тобою" },
  { es: "Estoy de acuerdo", uk: "я згоден" },
  { es: "Tienes razón", uk: "ти маєш рацію" },
  { es: "Lo siento mucho", uk: "мені дуже шкода" },
  { es: "Buena suerte", uk: "щасти!" },
  { es: "¿Qué pasa?", uk: "що сталося? / що нового?" },
  { es: "Poco a poco", uk: "потроху" },
  { es: "Paso a paso", uk: "крок за кроком" },
  { es: "Vale la pena", uk: "воно того варте" },
  { es: "Más vale tarde que nunca", uk: "краще пізно, ніж ніколи" },
  { es: "Querer es poder", uk: "де бажання, там і можливість" },
];

/** @deprecated використовуй DUMOSVIT_VOCAB; залишено для сумісності */
export const DUMOSVIT_WORDS = DUMOSVIT_VOCAB;
