export const ARC_DURATION_DAYS = 30;

export const ARC_CATALOG = [
  {
    id: "redemption",
    title: "Redemption",
    emoji: "🜂",
    coverFile: "redemption.png",
    summary: "",
    completionLine: "You turned remorse into disciplined progress.",
  },
  {
    id: "grinding",
    title: "Grinding",
    emoji: "⚒️",
    coverFile: "grinding.png",
    summary: "Consistency, deep work, and learning to love the process.",
    completionLine: "You proved that effort compounds into identity.",
  },
  {
    id: "resilience",
    title: "Resilience",
    emoji: "🛡️",
    coverFile: "foundations.png",
    summary: "Emotional endurance, steady recovery, and calm under pressure.",
    completionLine: "You stayed grounded and grew through pressure.",
  },
];

const ARC_QUOTES = {
  redemption: [
    "Redemption begins when you stop defending old patterns.",
    "You cannot rewrite yesterday, but you can outgrow it.",
    "A better identity is built by repeated honest choices.",
    "Return quickly after every setback. That is growth.",
    "Consistency is self-respect in motion.",
    "You are not your worst day; you are your next decision.",
    "Change is a promise kept in private.",
    "Discipline is how regret turns into respect.",
    "Your old story loses power when your habits change.",
    "Forgiveness is not forgetting; it is choosing forward.",
    "Every clean choice weakens an old chain.",
    "Healing grows in routines, not in speeches.",
    "You become trustworthy by showing up again.",
    "Progress is quiet, but it is never invisible to your future.",
    "Your standards decide your direction.",
    "Self-respect is built one kept promise at a time.",
    "You do not need to feel ready to do what is right.",
    "A stable life is built from stable days.",
    "Redemption is daily alignment, not a dramatic moment.",
    "Courage is returning to the path without excuses.",
    "Your next chapter starts with one honest hour.",
    "The person you want to be is trained, not found.",
    "You can be gentle with yourself and strict with your habits.",
    "Your peace is protected by your boundaries.",
    "When you choose truth over comfort, you grow fast.",
    "You are rebuilding, not restarting from zero.",
    "Every disciplined morning is a vote for your future self.",
    "Small integrity beats big intentions.",
    "The past explains you, but it does not own you.",
    "Redemption is the art of returning better each time.",
    "You are strongest when your actions match your values.",
    "Long-term joy is built from short-term discipline.",
    "Your new identity is written in repetition.",
    "You do not rise to goals; you fall to systems.",
    "Make today clean, and tomorrow gets easier.",
    "Clarity appears when action replaces overthinking.",
    "You are becoming the evidence of your own growth.",
    "The comeback begins when excuses end.",
    "Quiet consistency defeats loud motivation.",
    "You are one decision away from momentum.",
    "A hard truth accepted today saves years tomorrow.",
    "Own the mistake, keep the lesson, drop the shame.",
    "Your character grows where comfort ends.",
    "You can honor your past without living inside it.",
    "The strongest apology is changed behavior.",
    "Choose structure over chaos, even when tired.",
    "You rebuild trust by being consistent with yourself.",
    "Each disciplined hour is a brick in your new life.",
    "Do not chase perfect days; build reliable ones.",
    "Your progress counts most when no one sees it.",
    "Redemption thrives in honest routines.",
    "Every reset is proof you have not given up.",
    "You are allowed to begin again with wisdom.",
    "The future opens when excuses close.",
    "One clear boundary can change your whole week.",
    "Growth feels slow until you look back.",
    "Keep promises small, then keep them daily.",
    "You become free by choosing what is right repeatedly.",
    "Pain can teach; discipline can transform.",
    "Your next best choice is enough for this moment.",
  ],
  grinding: [
    "What you repeat daily defines your future more than your mood.",
    "Discipline is doing the work before motivation arrives.",
    "Small, boring wins are the architecture of greatness.",
    "The process is the prize. Results are delayed echoes.",
    "Mastery is built in sessions nobody sees.",
    "Great work is often invisible before it becomes obvious.",
    "Finish what you start, even when the mood is gone.",
    "Momentum is earned, not gifted.",
    "Boring repetition is the engine of elite results.",
    "The hardest rep is usually the one that changes you.",
    "Protect your focus like it is your future.",
    "One more honest effort beats one more excuse.",
    "Consistency turns average days into uncommon outcomes.",
    "Skill grows where distraction ends.",
    "Do the next clear step, not the perfect plan.",
    "Effort compounds quietly, then suddenly.",
    "Train your standards before you train your speed.",
    "Progress comes from finishing, not from starting endlessly.",
    "Deep work is self-respect with a schedule.",
    "You do not need hype, you need habits.",
    "Start small, stay strict, scale later.",
    "Your edge is built in ordinary mornings.",
    "Discomfort today can be confidence tomorrow.",
    "Show up enough times and the impossible gets familiar.",
    "Execution is motivation in physical form.",
  ],
  resilience: [
    "Resilience is calm action in noisy moments.",
    "You are stronger when your pace is steady, not rushed.",
    "Pressure reveals structure; build yours with intention.",
    "Recovery is part of performance, not a break from it.",
    "You do not break when your values stay intact.",
    "Strength is staying kind while staying firm.",
    "You can bend without breaking.",
    "Breathe first, decide second.",
    "Calm is a trained response, not a personality trait.",
    "When pressure rises, return to fundamentals.",
    "Steady beats dramatic in hard seasons.",
    "Hard moments pass; solid character remains.",
    "You recover faster when you recover intentionally.",
    "Resilience is built in the pause before reaction.",
    "Protect your energy, then direct it with purpose.",
    "Stability begins with one grounded choice.",
    "You are allowed to rest without quitting.",
    "Your composure is a competitive advantage.",
    "Endurance is courage stretched over time.",
    "Anchor your day with one non-negotiable habit.",
    "You are not fragile; you are adapting.",
    "Even slow healing is still healing.",
    "Keep your values louder than your stress.",
    "Resilience grows when you face reality clearly.",
    "You carry storms differently when your mind is trained.",
  ],
};

const ARC_ACTIONS = {
  redemption: [
    "Write one old habit you are leaving behind.",
    "Send one sincere apology or one sincere gratitude message.",
    "Take a 15-minute walk and choose one clean decision for today.",
    "Do 20 minutes without phone distractions.",
    "Journal three lines: what to stop, start, continue.",
    "Drink water, stretch for 2 minutes, reset your posture.",
    "Complete one postponed task in under 25 minutes.",
    "Declutter one small area around you.",
    "Set one boundary and keep it today.",
    "Write one sentence of self-respect and act on it.",
    "Replace one impulse with one intentional action.",
    "Spend 10 quiet minutes reflecting on your direction.",
    "Write down three triggers that pull you into old patterns.",
    "Delete one distraction app for the rest of the day.",
    "Wake up 20 minutes earlier and start without scrolling.",
    "Make your bed and keep your room tidy for the day.",
    "Do a 10-minute bodyweight workout to reset your energy.",
    "Read one page of notes about your goals and values.",
    "Set a timer for 30 minutes and finish one meaningful task.",
    "Say no to one thing that drains your focus.",
    "Prepare tomorrow’s top 3 priorities before sleep.",
    "Take a cold rinse for 30 seconds and practice discipline.",
    "Write one fear and one action that weakens it today.",
    "Spend 15 minutes learning a skill instead of consuming content.",
    "Turn off notifications for one focused hour.",
    "Clean your workspace before starting your main task.",
    "Write one sentence: who you are becoming this month.",
    "Avoid sugar for one meal and choose a clean alternative.",
    "Track every expense today to strengthen self-control.",
    "Call or message someone you respect and ask one growth question.",
    "Review your day and mark one win and one lesson.",
    "Go to sleep 30 minutes earlier to protect tomorrow’s clarity.",
  ],
  grinding: [
    "Do one 25-minute deep-work sprint with no distractions.",
    "Finish one difficult task before checking social media.",
    "Track one metric of progress in your notebook.",
  ],
  resilience: [
    "Take 5 slow breaths and relax your shoulders.",
    "Write one stressful thought and reframe it into action.",
    "Do a short reset: water, stretch, and 2 minutes of silence.",
  ],
};

// --- Additional Redemption content: 150 more quotes + 150 more micro-actions ---
ARC_QUOTES.redemption.push(
  "Redemption is a direction, not a destination.",
  "Your comeback is written in habits, not declarations.",
  "The quiet work today is the proof you needed tomorrow.",
  "You earn back trust in small, repeated deposits.",
  "Shame keeps you stuck; ownership sets you moving.",
  "Let your actions argue with your old reputation.",
  "A disciplined hour is louder than a guilty year.",
  "You are not behind; you are rebuilding the foundation.",
  "The cleanest revenge on your past is a steady present.",
  "Return to the path before the guilt convinces you to hide.",
  "Character is what survives when the excuses run out.",
  "You change your life at the speed of your habits.",
  "One honest choice can interrupt a hundred old ones.",
  "Discipline is love for the person you are becoming.",
  "The work you avoid is usually the work that frees you.",
  "You do not need a clean past to build a clean day.",
  "Momentum forgives a slow start.",
  "Make peace with effort and the results will follow.",
  "Your future self is watching how you handle this hour.",
  "Grace gets you up; discipline keeps you walking.",
  "Old patterns fade fastest under new routines.",
  "A promise to yourself is still a promise.",
  "You rebuild integrity one unseen choice at a time.",
  "Stop negotiating with the version of you that quits.",
  "The standard you keep tired is the standard you own.",
  "Redemption is consistency wearing work clothes.",
  "Your worst chapter can become your most useful one.",
  "Choose the boring right thing one more time.",
  "Healing is not loud; it is repeated.",
  "Self-respect is the interest paid on kept promises.",
  "You are allowed to outgrow who you used to be.",
  "Discipline today is mercy to your future self.",
  "The path back is shorter than the story of guilt.",
  "Action dissolves the fog that thinking creates.",
  "You become reliable by being reliable when it is hard.",
  "Let the past be a teacher, never a landlord.",
  "Every kept boundary returns a piece of your power.",
  "Progress hides in the days you almost skipped.",
  "You are one disciplined morning from a different month.",
  "Quiet effort beats loud regret.",
  "Your habits are the apology your words cannot make.",
  "Do the next right thing and let it multiply.",
  "The comeback is built in private, claimed in public.",
  "You are not stuck; you are between decisions.",
  "Consistency is how you keep faith with yourself.",
  "Strength is returning without dramatizing the fall.",
  "Replace the old loop before it replaces your day.",
  "Your direction matters more than your speed.",
  "A small win at the right time changes everything after it.",
  "You cannot outrun your patterns, but you can replace them.",
  "Discipline is freedom you build in advance.",
  "The honest hour is the one that rebuilds you.",
  "You do not rise by accident; you rise by routine.",
  "Let your standards be higher than your moods.",
  "The chains break in the ordinary, not the dramatic.",
  "You owe your future self today's discipline.",
  "Stop rehearsing the failure; rehearse the return.",
  "A clear conscience is built by clean choices.",
  "Your recovery is real when it survives a bad day.",
  "Carry the lesson, set down the weight.",
  "You are the sum of what you repeat, not what you regret.",
  "Make the decision once, then defend it daily.",
  "Redemption favors the consistent, not the loud.",
  "Beginning again is not the same as beginning from nothing.",
  "The work in silence speaks the clearest later.",
  "Hold the standard firmly; hold yourself kindly.",
  "You prove the change by living it on a hard day.",
  "One honest reset outweighs ten guilty spirals.",
  "Discipline is self-trust under construction.",
  "The right routine makes the right choice automatic.",
  "You are rebuilding a name only you can sign.",
  "Less explaining, more becoming.",
  "Your standards travel with you; protect them.",
  "The version of you that follows through is already inside.",
  "Guilt asks for punishment; growth asks for practice.",
  "You climb out the same way you fell, one step repeated.",
  "Trust is rebuilt in increments, never in apologies alone.",
  "Stay loyal to the plan when the feeling leaves.",
  "A disciplined life is an apology that keeps speaking.",
  "You are the proof that change is possible, daily.",
  "Let consistency do what motivation could not.",
  "The past sets the scene; you write the next line.",
  "Hard now buys easy later; soft now borrows from it.",
  "Your identity follows your repetition, not your intention.",
  "Return to your values before you return to your phone.",
  "Redemption is the discipline of beginning again, calmly.",
  "You build a new reputation in rooms no one sees.",
  "The smallest honest act can reset the whole day.",
  "Carry the lesson lightly and the standard firmly.",
  "You are not what happened; you are what you practice.",
  "Discipline is how you keep a promise to your future.",
  "Every reset is a rehearsal for a steadier you.",
  "The work you do quietly compounds loudly.",
  "Choose the harder right over the easier wrong, once more.",
  "You earn calm by handling the small things well.",
  "Stop auditioning for forgiveness and start building proof.",
  "The day improves the moment you stop bargaining with it.",
  "You are becoming someone your past would not recognize.",
  "Steady hands rebuild what shaky ones dropped.",
  "Let the routine carry you when willpower will not.",
  "A better life is assembled from unremarkable days.",
  "You do not need permission to begin doing right.",
  "The honest path is rarely crowded; walk it anyway.",
  "Your discipline is a quiet rebellion against your old self.",
  "Keep showing up until showing up is who you are.",
  "The setback is a comma, not a conclusion.",
  "You repair the future by respecting the present.",
  'Discipline turns "I wish" into "I did."',
  "Be the person your routines are training you to be.",
  "The work outlasts the mood that resisted it.",
  "You are one boundary away from a calmer week.",
  "Redemption is paid in attention, not in regret.",
  "Trust your systems on the days you cannot trust your feelings.",
  "The smallest discipline kept is bigger than the largest intention dropped.",
  "You become unshakeable by repeating the unglamorous.",
  "Stop measuring the climb by the slip.",
  "Your next clean choice is always within reach.",
  "A steady today silences a loud yesterday.",
  "You do not have to feel new to act new.",
  "Let your effort be the evidence and the apology.",
  "Discipline is the quiet bridge out of who you were.",
  "You are rebuilt by what you refuse and what you repeat.",
  "The honest day asks for action, not for guilt.",
  "Shrink the promise until you cannot fail it, then keep it.",
  "Your recovery deepens every time you choose it tired.",
  "The past is paid; stop paying it twice with shame.",
  "You are the architect of your next thirty days.",
  "Let the routine be boring so the results can be remarkable.",
  "Choose progress over performance today.",
  "You restore yourself in the choices nobody applauds.",
  "Discipline is dignity you practice into permanence.",
  "The cleanest comeback is the one nobody saw being built.",
  "You are not starting over; you are starting wiser.",
  "Show up so often that the old self loses the argument.",
  "A grounded morning protects an honest day.",
  "You build trust by being predictable in good ways.",
  "The work is the worship; do it with attention.",
  "Replace regret with reps.",
  "You are closer to steady than your bad day suggests.",
  "Let your habits whisper what your guilt used to shout.",
  "The return is the real victory, every single time.",
  "You earn tomorrow's clarity with tonight's discipline.",
  "Be consistent when it is invisible and you will be unstoppable when it counts.",
  "Your standards are the walls that keep your peace.",
  "Do not wait to feel worthy; act worthy and let feeling catch up.",
  "The disciplined path forgives the late start.",
  "You are remade in the ordinary act repeated well.",
  "Quiet integrity is the loudest comeback.",
  "Trade the spiral for a single grounded step.",
  "You are always one honest hour from getting back on track.",
  "The road back is walked one ordinary day at a time.",
  "You owe your future self a better present.",
  "Regret is information; discipline is the reply.",
  "A changed life begins with an unchanged commitment.",
  "Stop waiting for closure and start building openings.",
  "What you repeat, you become. Repeat what heals.",
  "Accountability is the doorway, not the punishment.",
  "Every honest morning shrinks yesterday's shadow.",
  "You are not behind; you are rebuilding on stronger ground.",
  "Humility is strength that no longer needs to prove itself.",
  "A mistake becomes wisdom the moment you act on its lesson.",
  "Do the next right thing, then do it again.",
  "Earned peace lasts longer than borrowed comfort.",
  "Integrity is doing the work when nobody is keeping score.",
  "You cannot think your way into a new life; you live your way into it.",
  "Let your effort speak where your words once failed.",
  "Discipline is remembering what you want most.",
  "The bravest promise is the one you keep to yourself.",
  "Old patterns are loud; new habits are patient.",
  "You do not need permission to become better.",
  "Restoration starts with a single repaired routine.",
  "The weight of the past lightens with every step forward.",
  "Make amends with action, not with endless explanation.",
  "Your worth is rebuilt in the small, unseen hours.",
  "Today is a clean page; write one honest line.",
  "Patience with yourself is part of the discipline.",
  "Second chances are built, not given.",
  "Fall, learn, return. That is the rhythm of redemption.",
  "You are allowed to outgrow who you were.",
  "Self-forgiveness is a decision you renew every day.",
  "Strong people are not spotless; they are consistent.",
  "A calm mind follows a kept promise.",
  "Your habits are louder than your history.",
  "Every boundary you hold is a wall you no longer need to rebuild.",
  "Redemption is love for your future expressed in today's choices.",
  "Turn shame into structure and guilt into goals.",
  "One disciplined choice can interrupt a whole chain of chaos.",
  "The path back is narrow, but it is always open.",
  "Show up imperfectly rather than disappear perfectly.",
  "Real change is boring from the outside and powerful from the inside.",
  "Your consistency is the apology your future accepts.",
  "When you know better, the only honest move is to do better.",
  "Discomfort today is the price of respect tomorrow.",
  "You are rewriting your reputation with yourself first.",
  "Small repairs, made daily, rebuild whole foundations.",
  "Let your new routine be your quiet testimony.",
  "There is dignity in starting again with clear eyes.",
  "The past is a teacher, not a jailer.",
  "Choose the harder right over the easier wrong.",
  "Character is what you practice when you are tired.",
  "A redeemed life is simply a life aligned with its values.",
  "Every clean day adds interest to your self-trust.",
  "Don't be defined by the fall; be refined by the rise.",
  "Your effort is the bridge between who you were and who you are becoming.",
  "Freedom is found on the far side of discipline.",
  "Return to your values faster than you once left them.",
  "Growth asks for honesty before it gives you peace.",
  "The person you hurt most by old habits was you. Make it right.",
  "Every promise kept is a stitch in a torn reputation.",
  "Stay humble about the past and stubborn about the future.",
  "Healing is not linear, but commitment can be.",
  "Do it for the version of you that is still watching.",
  "Your story is not finished, so stop reading the old chapters.",
  "Quiet discipline turns regret into respect.",
  "Shame says hide; redemption says rebuild.",
  "The moment you take responsibility, you take back power.",
  "Progress made in silence still echoes.",
  "Momentum is mercy you give your future self.",
  "Every day you choose differently, the old you loses a vote.",
  "Repentance is a turn, and turns are made with feet.",
  "Be proud of the restart, not only the finish.",
  "You become reliable the way rivers carve stone: steadily.",
  "Let today be the day the pattern breaks.",
  "Honest work is the cleanest form of self-respect.",
  "You can carry the lesson without carrying the guilt.",
  "Rebuild slowly; foundations do not like to be rushed.",
  "Your discipline is a gift to everyone who loves you.",
  "The first step back is the hardest and the most important.",
  "Make peace with your past by building a better present.",
  "Choose to be the evidence that people can change.",
  "Clear actions dissolve foggy guilt.",
  "Redemption is not a feeling; it is a practice.",
  "A strong finish matters more than a clean start.",
  "Live today so that tomorrow needs no excuse.",
  "The mirror respects what the calendar records.",
  "You rise every time you refuse to repeat the fall.",
  "Rebuilt trust is often stronger than unbroken trust.",
  "Turn the page, then write with intention.",
  "Your best apology to yourself is a better routine.",
  "Kind to your heart, firm with your habits.",
  "Every sunrise is a chance to be consistent again.",
  "Fewer promises, more proof.",
  "The work is the way back home.",
  "Discipline today, gratitude tomorrow.",
  "Your new life is closer than your old excuses.",
  "Hold your standards gently but never let them go.",
  "Steady steps outrun sudden regret.",
  "Redemption grows wherever honesty is planted.",
  "You were not built to stay broken.",
  "Become someone your past self would be grateful for.",
);

ARC_ACTIONS.redemption.push(
  "Drink a full glass of water before your first coffee.",
  "Write down the one task you are avoiding and start it for five minutes.",
  "Put your phone in another room for the first hour awake.",
  "Do ten push-ups right now, no warm-up needed.",
  "Make a two-line plan for the next two hours.",
  "Unsubscribe from one email list that wastes your attention.",
  "Tidy your desk surface until it is completely clear.",
  "Set a 25-minute focus timer and silence every notification.",
  "Take a 10-minute walk outside without your phone.",
  "Write the name of the person you want to become at the top of today's notes.",
  "Eat one meal slowly, without any screen.",
  "Schedule tomorrow's hardest task into a specific time slot.",
  "Stretch your back and neck for three minutes.",
  "Delete 20 photos or files you no longer need.",
  "Say one honest thing you have been avoiding saying.",
  "Refill your water bottle and finish it before lunch.",
  "Spend five minutes planning your meals for the day.",
  "Write three things you are grateful for, specifically.",
  "Stand up and take ten slow breaths by an open window.",
  "Read two pages of a book instead of opening social media.",
  "Make your bed with tight corners and admire it.",
  "Block one website that pulls you off track for the day.",
  "Do a two-minute plank or hold it as long as you can.",
  "Write tomorrow's first task on a sticky note tonight.",
  "Cancel or decline one commitment that no longer serves you.",
  "Wash the dishes in your sink right now.",
  "Set your phone to grayscale for the rest of the day.",
  "Take the stairs instead of the elevator today.",
  "Write one apology you owe and decide when to deliver it.",
  "Spend 15 minutes on the project you keep postponing.",
  "Do 20 squats before your next meal.",
  "Put tomorrow's clothes out before you sleep.",
  "Mute three group chats that drain your focus.",
  "Write the single most important task for today and circle it.",
  "Drink water instead of your next sugary drink.",
  "Clear your phone's home screen down to essential apps only.",
  "Take a five-minute cold-water rinse at the end of your shower.",
  "Write one boundary you will hold this week and tell someone.",
  "Walk for 20 minutes and leave your headphones at home.",
  "Empty one drawer and throw away what you do not use.",
  "Reply to the message you have been avoiding.",
  "Do five minutes of slow breathing before checking your phone.",
  "Write down how you want to feel at the end of today.",
  "Prepare a healthy snack so you skip the impulsive one.",
  "Set one alarm to step away from screens this evening.",
  "Read your monthly goal out loud once.",
  "Spend ten minutes organizing your downloads folder.",
  "Do a 7-minute workout right now.",
  "Write the lesson from your last setback in one sentence.",
  "Put a glass of water on your nightstand for the morning.",
  "Take a different route on your walk and notice three new things.",
  "Log everything you eat today, honestly.",
  "Turn your phone face-down for your next work session.",
  "Write one thing you will say no to this week.",
  "Floss your teeth tonight, no skipping.",
  "Plan your wake-up time and set the alarm across the room.",
  "Spend five minutes journaling about what triggered you today.",
  "Do ten minutes of focused reading on your craft.",
  "Wipe down one surface in your home until it shines.",
  "Send one message of encouragement to someone you respect.",
  "Write your top three values where you will see them tomorrow.",
  "Take three deep breaths before answering the next hard message.",
  "Replace one hour of scrolling with one hour of sleep tonight.",
  "Do a brisk five-minute walk after your next meal.",
  "Write down one excuse you keep using and cross it out.",
  "Set a timer and sit in silence for five minutes.",
  "Pay one small bill or handle one task you have been dreading.",
  "Drink a glass of water and eat one piece of fruit now.",
  "Clear ten messages from your inbox.",
  "Write what a disciplined version of today would look like.",
  "Do calf raises while you wait for the kettle.",
  "Put your shopping apps in a hidden folder.",
  "Walk outside and get ten minutes of morning light.",
  "Write one promise you will keep before noon.",
  "Tidy the floor of one room completely.",
  "Turn off autoplay on your video apps.",
  "Take a two-minute break to roll your shoulders and breathe.",
  "Write the first sentence of the task you keep avoiding.",
  "Choose water over alcohol for tonight.",
  "Set your phone to do-not-disturb for the next 90 minutes.",
  "Do 15 lunges, slow and controlled.",
  "Write down one person you can be more honest with.",
  "Prepare your work area before you sit down to focus.",
  "Cancel one notification that does not earn your attention.",
  "Read one paragraph of your goals before you start the day.",
  "Spend five minutes stretching before bed.",
  "Write the one thing that would make today a win.",
  "Drink water before each meal today.",
  "Log out of one app you open out of boredom.",
  "Take a 60-second cold shower at the end of your wash.",
  "Write a short note to your future self about today.",
  "Do a 20-minute walk and plan one decision while you move.",
  "Clear your camera roll of 30 screenshots you do not need.",
  "Make a list of three tasks and do the smallest one now.",
  "Put your phone on airplane mode during your next focus block.",
  "Write one boundary you broke recently and how to hold it next time.",
  "Do ten slow sit-ups on the floor.",
  "Drink a glass of water the moment you wake up tomorrow.",
  "Spend ten minutes decluttering your email inbox.",
  "Write one sentence describing the day you want to have.",
  "Take a walk and call someone who lifts your standards.",
  "Replace your next snack with a glass of water and a stretch.",
  "Set out your gym clothes or work tools the night before.",
  "Write down the time you will start your hardest task tomorrow.",
  "Do a two-minute wall sit.",
  "Mute notifications from one app for the whole day.",
  "Read three pages and write one line about what you learned.",
  "Tidy your digital desktop to a single clean screen.",
  "Choose the stairs and a glass of water over the easy option once today.",
  "Write what you will do differently the next time you slip.",
  "Do five minutes of breathing with your eyes closed.",
  "Prepare tomorrow's breakfast tonight.",
  "Send the email you have been postponing for three days.",
  "Walk for ten minutes right after you wake up.",
  "Write the single habit you most want to rebuild this month.",
  "Put your phone to charge outside the bedroom tonight.",
  "Do 30 seconds of jumping jacks to reset your energy.",
  "Clear one shelf and keep only what you use.",
  "Write a kind, honest message to someone you let down.",
  "Spend ten minutes preparing for tomorrow's first meeting or task.",
  "Drink water and skip the second coffee today.",
  "Set a single, specific goal for the next hour.",
  "Take three minutes to write what is actually bothering you.",
  "Do a slow 15-minute stretch session before sleep.",
  "Turn off one screen 30 minutes before bed tonight.",
  "Write the name of one distraction and remove it from reach.",
  "Walk one extra block on your way home today.",
  "Make a short, honest list of where your time went yesterday.",
  "Do ten minutes of focused practice on a skill you are building.",
  "Clear your browser tabs down to only what you need now.",
  "Write one thing you are proud of handling well today.",
  "Eat one vegetable with your next meal.",
  "Set your most important task as your phone wallpaper for today.",
  "Take a five-minute silent break with no input at all.",
  "Write down tomorrow's wake-up time and stick to it.",
  "Put your dirty laundry in the basket, not on the floor.",
  "Put away every item that is out of place on one table.",
  "Reply to one person you have been ignoring.",
  "Spend 15 minutes on deep work before any messages.",
  "Write the smallest possible next step and do it now.",
  "Drink a glass of water and take a short walk before deciding anything big.",
  "Choose one healthy swap for a meal today.",
  "Set a 45-minute timer and work without switching tasks.",
  "Write one fear that holds you back and one tiny step past it.",
  "Do a posture check and sit tall for the next hour.",
  "Clear your notifications and start the next task with a quiet screen.",
  'Write what "back on track" looks like for you this week.',
  "Take ten deep breaths before your next difficult conversation.",
  "Spend five minutes tonight planning a calmer morning.",
  "Write one promise to your future self and keep it tomorrow.",
  "Write a short letter to your past self and forgive one specific mistake.",
  "List three promises you broke recently and keep the smallest one today.",
  "Spend 20 minutes on the task you have postponed the longest.",
  "Unfollow three accounts that pull you toward old habits.",
  "Make a simple, healthy meal instead of ordering food.",
  "Write down one thing you are proud of from this week.",
  "Go for a 20-minute walk without headphones and just think.",
  "Return something you borrowed or reply to a message you ignored.",
  "Pay or plan one small debt or bill you have been avoiding.",
  "Clean one drawer, shelf or folder that has been messy for weeks.",
  "Write your three core values and one action for each today.",
  "Replace 30 minutes of scrolling with reading a book.",
  "Do a 5-minute breathing exercise before your first task.",
  "Tell one person the truth about something you have been hiding from yourself.",
  "Plan your evening so the last hour is screen-free.",
  "Do 30 squats and 20 push-ups spread through the day.",
  "Write a list of five people who supported you and thank one of them.",
  "Set an alarm for a fixed bedtime and honor it tonight.",
  "Fill a water bottle and finish it by lunch.",
  "Identify one trigger today and write how you will handle it next time.",
  "Spend ten minutes stretching before bed.",
  "Sort your digital photos or files for 15 minutes.",
  "Write one rule for yourself for this week and post it where you see it.",
  "Cook enough food today to have a healthy lunch tomorrow.",
  "Leave your phone at home or in your bag during one walk or errand.",
  "Write down what a perfect ordinary day would look like and live one part of it.",
  "Volunteer 30 minutes of help to a friend, neighbor or family member.",
  "Read about a person who rebuilt their life and note one lesson.",
  "Track your mood three times today with one word each.",
  "Choose one meal today and eat it slowly without screens.",
  "Write down one belief about yourself that is no longer true.",
  "Do the hardest task of the day before noon.",
  "Delete old messages or chats that keep you stuck in the past.",
  "Spend 15 minutes outside in daylight first thing in the morning.",
  "Prepare your clothes and bag for tomorrow tonight.",
  "Write three things you are grateful for before sleep.",
  "Skip one unnecessary purchase today and note the money saved.",
  "Make a list of small wins from the last 30 days.",
  "Practice saying 'no' kindly in one situation today.",
  "Spend 10 minutes learning something useful for your work or studies.",
  "Clean your shoes, bag or car — take care of one thing you use daily.",
  "Write a one-paragraph vision of yourself one year from now.",
  "Take the stairs every time you can today.",
  "Turn your phone to grayscale for the whole afternoon.",
  "Finish one unfinished conversation with honesty and calm.",
  "Write a list of excuses you use most and an answer to each.",
  "Do one kind act anonymously.",
  "Plan your week: three priorities and one rest block.",
  "Spend 20 minutes on a hobby that makes you feel like yourself.",
  "Reflect for five minutes: what would the best version of you do next?",
  "Avoid complaining for the whole day; replace it with one solution.",
  "Wash the dishes immediately after every meal today.",
  "Write a short note to your future self and seal it for a month.",
  "Go to bed without your phone in the bedroom.",
  "Organize your desktop and close every tab you do not need.",
  "Choose water instead of a sugary drink for the whole day.",
  "Write down a mistake and three concrete ways you will prevent it.",
  "Spend 10 minutes in silence without any input.",
  "Ask someone you trust for honest feedback and just listen.",
  "Do a 15-minute workout even if you do not feel like it.",
  "Review your goals and cross out one that no longer matters.",
  "Write one thing you forgive another person for, even if you never send it.",
  "Prepare a healthy snack so you are not tempted later.",
  "Set a 45-minute focus block and protect it completely.",
  "Write down your biggest distraction and one barrier against it.",
  "Spend time with someone who brings out your best side.",
  "Make one appointment you have been postponing (doctor, dentist, call).",
  "Journal: what am I avoiding, and what is the first tiny step?",
  "Do a 10-minute tidy-up before you start relaxing tonight.",
  "Listen to an educational podcast instead of background noise.",
  "Write a list of three habits you want to be known for.",
  "Say one sincere compliment to someone today.",
  "Practice patience: wait one full minute before reacting to something irritating.",
  "Spend 15 minutes planning a small project you have dreamed about.",
  "Repair or fix one broken thing around you.",
  "Get sunlight and movement within 30 minutes of waking up.",
  "Write down how you want to feel tonight and choose actions that lead there.",
  "Remove one item from your room that reminds you of your old patterns.",
  "Take a mindful shower and mentally wash off yesterday.",
  "End the day by writing one lesson and one intention for tomorrow.",
);

export function getArcById(arcId) {
  return ARC_CATALOG.find((a) => a.id === arcId) ?? null;
}

export function listArcIds() {
  return ARC_CATALOG.map((a) => a.id);
}

export function pickArcMessage(arcId, dayNumber, messageCount = 0) {
  const msgIdx = Math.max(0, Number(messageCount) || 0);
  const quotes = ARC_QUOTES[arcId] ?? ARC_QUOTES.redemption;
  const actions = ARC_ACTIONS[arcId] ?? ARC_ACTIONS.redemption;
  return {
    quote: quotes[msgIdx % quotes.length],
    action: actions[msgIdx % actions.length],
  };
}
