export const ARC_DURATION_DAYS = 30;

export const ARC_CATALOG = [
  {
    id: "redemption",
    title: "Redemption",
    emoji: "🜂",
    coverFile: "redemption.png",
    summary: "Self-forgiveness, responsibility, and rebuilding your life direction.",
    completionLine: "You turned remorse into disciplined progress.",
  },
  {
    id: "grinding",
    title: "Grinding",
    emoji: "⚒️",
    coverFile: "grinding.png",
    summary: "Consistency, deep work, and learning to love the process.",
    completionLine: "You proved that effort compounds into identity.",
  },
  {
    id: "resilience",
    title: "Resilience",
    emoji: "🛡️",
    coverFile: "foundations.png",
    summary: "Emotional endurance, steady recovery, and calm under pressure.",
    completionLine: "You stayed grounded and grew through pressure.",
  },
];

const ARC_QUOTES = {
  redemption: [
    "Redemption begins when you stop defending old patterns.",
    "You cannot rewrite yesterday, but you can outgrow it.",
    "A better identity is built by repeated honest choices.",
    "Return quickly after every setback. That is growth.",
    "Consistency is self-respect in motion.",
    "You are not your worst day; you are your next decision.",
    "Change is a promise kept in private.",
    "Discipline is how regret turns into respect.",
    "Your old story loses power when your habits change.",
    "Forgiveness is not forgetting; it is choosing forward.",
    "Every clean choice weakens an old chain.",
    "Healing grows in routines, not in speeches.",
    "You become trustworthy by showing up again.",
    "Progress is quiet, but it is never invisible to your future.",
    "Your standards decide your direction.",
    "Self-respect is built one kept promise at a time.",
    "You do not need to feel ready to do what is right.",
    "A stable life is built from stable days.",
    "Redemption is daily alignment, not a dramatic moment.",
    "Courage is returning to the path without excuses.",
    "Your next chapter starts with one honest hour.",
    "The person you want to be is trained, not found.",
    "You can be gentle with yourself and strict with your habits.",
    "Your peace is protected by your boundaries.",
    "When you choose truth over comfort, you grow fast.",
    "You are rebuilding, not restarting from zero.",
    "Every disciplined morning is a vote for your future self.",
    "Small integrity beats big intentions.",
    "The past explains you, but it does not own you.",
    "Redemption is the art of returning better each time.",
    "You are strongest when your actions match your values.",
    "Long-term joy is built from short-term discipline.",
    "Your new identity is written in repetition.",
    "You do not rise to goals; you fall to systems.",
    "Make today clean, and tomorrow gets easier.",
    "Clarity appears when action replaces overthinking.",
    "You are becoming the evidence of your own growth.",
    "The comeback begins when excuses end.",
    "Quiet consistency defeats loud motivation.",
    "You are one decision away from momentum.",
    "A hard truth accepted today saves years tomorrow.",
    "Own the mistake, keep the lesson, drop the shame.",
    "Your character grows where comfort ends.",
    "You can honor your past without living inside it.",
    "The strongest apology is changed behavior.",
    "Choose structure over chaos, even when tired.",
    "You rebuild trust by being consistent with yourself.",
    "Each disciplined hour is a brick in your new life.",
    "Do not chase perfect days; build reliable ones.",
    "Your progress counts most when no one sees it.",
    "Redemption thrives in honest routines.",
    "Every reset is proof you have not given up.",
    "You are allowed to begin again with wisdom.",
    "The future opens when excuses close.",
    "One clear boundary can change your whole week.",
    "Growth feels slow until you look back.",
    "Keep promises small, then keep them daily.",
    "You become free by choosing what is right repeatedly.",
    "Pain can teach; discipline can transform.",
    "Your next best choice is enough for this moment.",
  ],
  grinding: [
    "What you repeat daily defines your future more than your mood.",
    "Discipline is doing the work before motivation arrives.",
    "Small, boring wins are the architecture of greatness.",
    "The process is the prize. Results are delayed echoes.",
    "Mastery is built in sessions nobody sees.",
    "Great work is often invisible before it becomes obvious.",
    "Finish what you start, even when the mood is gone.",
    "Momentum is earned, not gifted.",
    "Boring repetition is the engine of elite results.",
    "The hardest rep is usually the one that changes you.",
    "Protect your focus like it is your future.",
    "One more honest effort beats one more excuse.",
    "Consistency turns average days into uncommon outcomes.",
    "Skill grows where distraction ends.",
    "Do the next clear step, not the perfect plan.",
    "Effort compounds quietly, then suddenly.",
    "Train your standards before you train your speed.",
    "Progress comes from finishing, not from starting endlessly.",
    "Deep work is self-respect with a schedule.",
    "You do not need hype, you need habits.",
    "Start small, stay strict, scale later.",
    "Your edge is built in ordinary mornings.",
    "Discomfort today can be confidence tomorrow.",
    "Show up enough times and the impossible gets familiar.",
    "Execution is motivation in physical form.",
  ],
  resilience: [
    "Resilience is calm action in noisy moments.",
    "You are stronger when your pace is steady, not rushed.",
    "Pressure reveals structure; build yours with intention.",
    "Recovery is part of performance, not a break from it.",
    "You do not break when your values stay intact.",
    "Strength is staying kind while staying firm.",
    "You can bend without breaking.",
    "Breathe first, decide second.",
    "Calm is a trained response, not a personality trait.",
    "When pressure rises, return to fundamentals.",
    "Steady beats dramatic in hard seasons.",
    "Hard moments pass; solid character remains.",
    "You recover faster when you recover intentionally.",
    "Resilience is built in the pause before reaction.",
    "Protect your energy, then direct it with purpose.",
    "Stability begins with one grounded choice.",
    "You are allowed to rest without quitting.",
    "Your composure is a competitive advantage.",
    "Endurance is courage stretched over time.",
    "Anchor your day with one non-negotiable habit.",
    "You are not fragile; you are adapting.",
    "Even slow healing is still healing.",
    "Keep your values louder than your stress.",
    "Resilience grows when you face reality clearly.",
    "You carry storms differently when your mind is trained.",
  ],
};

const ARC_ACTIONS = {
  redemption: [
    "Write one old habit you are leaving behind.",
    "Send one sincere apology or one sincere gratitude message.",
    "Take a 15-minute walk and choose one clean decision for today.",
    "Do 20 minutes without phone distractions.",
    "Journal three lines: what to stop, start, continue.",
    "Drink water, stretch for 2 minutes, reset your posture.",
    "Complete one postponed task in under 25 minutes.",
    "Declutter one small area around you.",
    "Set one boundary and keep it today.",
    "Write one sentence of self-respect and act on it.",
    "Replace one impulse with one intentional action.",
    "Spend 10 quiet minutes reflecting on your direction.",
    "Write down three triggers that pull you into old patterns.",
    "Delete one distraction app for the rest of the day.",
    "Wake up 20 minutes earlier and start without scrolling.",
    "Make your bed and keep your room tidy for the day.",
    "Do a 10-minute bodyweight workout to reset your energy.",
    "Read one page of notes about your goals and values.",
    "Set a timer for 30 minutes and finish one meaningful task.",
    "Say no to one thing that drains your focus.",
    "Prepare tomorrow’s top 3 priorities before sleep.",
    "Take a cold rinse for 30 seconds and practice discipline.",
    "Write one fear and one action that weakens it today.",
    "Spend 15 minutes learning a skill instead of consuming content.",
    "Turn off notifications for one focused hour.",
    "Clean your workspace before starting your main task.",
    "Write one sentence: who you are becoming this month.",
    "Avoid sugar for one meal and choose a clean alternative.",
    "Track every expense today to strengthen self-control.",
    "Call or message someone you respect and ask one growth question.",
    "Review your day and mark one win and one lesson.",
    "Go to sleep 30 minutes earlier to protect tomorrow’s clarity.",
  ],
  grinding: [
    "Do one 25-minute deep-work sprint with no distractions.",
    "Finish one difficult task before checking social media.",
    "Track one metric of progress in your notebook.",
  ],
  resilience: [
    "Take 5 slow breaths and relax your shoulders.",
    "Write one stressful thought and reframe it into action.",
    "Do a short reset: water, stretch, and 2 minutes of silence.",
  ],
};

export function getArcById(arcId) {
  return ARC_CATALOG.find((a) => a.id === arcId) ?? null;
}

export function listArcIds() {
  return ARC_CATALOG.map((a) => a.id);
}

export function pickArcMessage(arcId, dayNumber, messageCount = 0) {
  const msgIdx = Math.max(0, Number(messageCount) || 0);
  const quotes = ARC_QUOTES[arcId] ?? ARC_QUOTES.redemption;
  const actions = ARC_ACTIONS[arcId] ?? ARC_ACTIONS.redemption;
  return {
    quote: quotes[msgIdx % quotes.length],
    action: actions[msgIdx % actions.length],
  };
}
