export const REDEMPTION_DURATION_DAYS = 30;

const REDEMPTION_QUOTES = [
  "Redemption begins the moment you stop negotiating with your old excuses.",
  "Your future is built by what you repeat when nobody applauds.",
  "Growth is often quiet: less drama, more discipline.",
  "You do not need a new life overnight. You need a new choice today.",
  "Healing is not linear, but commitment can still be.",
  "Every honest step forward is a vote for the person you are becoming.",
  "Consistency is self-respect in motion.",
  "You cannot rewrite yesterday, but you can outgrow it.",
  "Small promises kept to yourself become character.",
  "Redemption is not perfection. It is daily return.",
  "Your habits write your biography before your words do.",
  "A calm mind and a clear action beat motivation every time.",
  "The bravest thing you can do is start again without self-hate.",
  "Discomfort is often the doorway to your next level.",
  "You are not behind. You are in training.",
  "What you practice in private appears in public.",
  "Let discipline carry you when feelings fade.",
  "Every day is a chance to choose alignment over impulse.",
  "Maturity is choosing long-term peace over short-term relief.",
  "You become trustworthy by keeping promises to yourself first.",
  "Redemption is a direction, not a single event.",
  "Your limits are often old stories, not current facts.",
  "Progress is built by boring, repeatable wins.",
  "The version of you that you admire is built one decision at a time.",
  "You are allowed to evolve beyond who you were in pain.",
  "When you fall, return faster. That is growth.",
  "Clarity comes from action, not endless thinking.",
  "Your standards shape your destiny.",
  "Courage is consistency under pressure.",
  "The life you want is hidden inside the work you avoid.",
  "Redemption is choosing purpose when comfort calls louder.",
  "You are strongest when your actions match your values.",
  "A better identity is earned through repeated proof.",
  "Energy follows meaning. Remember why you started.",
  "Your next chapter begins with one honest decision now.",
  "Redemption grows when your routine changes, not only your intentions.",
  "Self-trust is built every time you keep one tiny promise.",
  "The comeback starts in ordinary moments, not dramatic ones.",
  "Your pace can be slow, but your direction must stay true.",
  "Character is what remains when excuses run out.",
  "Discipline is love for your future self.",
  "You heal faster when your actions support your words.",
  "The life you miss is often hidden behind one difficult habit shift.",
  "Freedom comes from structure you choose, not chaos you tolerate.",
  "Do not wait to feel ready. Act and let readiness catch up.",
  "Your identity follows your repeated behavior.",
  "Peace is the reward of clean choices.",
  "You do not need to prove everyone wrong. Just prove yourself right.",
  "Growth begins where your comfort script ends.",
  "One honest day repeated becomes a transformed year.",
  "When temptation is loud, remember your long game.",
  "You become powerful when you stop abandoning your standards.",
  "The past explains you, but it does not own you.",
  "A disciplined morning can rescue an unfocused life.",
  "You are one decision away from returning to yourself.",
  "The strongest apology is changed behavior.",
  "Build a life that does not require escape.",
  "Momentum is born from finishing small commitments.",
  "You are not your worst chapter. You are your next choice.",
  "Redemption is quiet work that eventually becomes visible results.",
  "Choose what future-you will thank you for tonight.",
  "You cannot control every feeling, but you can direct every action.",
  "Consistency beats intensity when the goal is lasting change.",
  "Your boundaries protect the person you are becoming.",
  "Do not confuse delay with defeat.",
  "A reset is not failure. It is wisdom in motion.",
  "The habit you repeat today writes tomorrow's confidence.",
  "Respect your own word and your life will stabilize.",
  "Redemption is built in private before it is celebrated in public.",
  "Each clean choice weakens the old identity.",
  "Courage often looks like saying no to your former patterns.",
  "You become lighter when your actions stop fighting your values.",
  "The new you is not found. It is practiced.",
  "Integrity is doing the right thing before the results arrive.",
  "Your routine is your future in visible form.",
  "A focused hour can restore a drifting week.",
  "Change gets easier when your environment supports your standards.",
  "You are rebuilding, not starting from zero.",
  "True progress is less noise and more follow-through.",
  "Strength is repeating the right choice when nobody checks on you.",
  "Your comeback is a stack of ordinary disciplined days.",
  "Forgive yourself, then move with precision.",
  "A clear purpose makes short-term cravings less persuasive.",
  "Redemption is patience married to action.",
  "What you do next matters more than what happened before.",
];

const REDEMPTION_MICRO_ACTIONS = [
  "Drink a glass of water and breathe deeply for one minute.",
  "Write down one behavior you want to leave behind.",
  "Spend 10 minutes in focused silence without scrolling.",
  "Do one hard task first, before comfort.",
  "Send one sincere message of gratitude.",
  "Take a 15-minute walk and reflect on your direction.",
  "Clean one small area around you to reset your mind.",
  "Journal one page about the person you are becoming.",
  "Read 2 pages of a book that strengthens you.",
  "Replace one complaint with one concrete action.",
  "Make your bed and start the day with order.",
  "Set a 20-minute focus timer and complete one priority task.",
  "Delete one distracting app from your home screen.",
  "Write three lines about what you learned from yesterday.",
  "Do 25 bodyweight squats to wake up your energy.",
  "Prepare a healthy snack instead of buying junk food.",
  "Turn off notifications for one hour and work in silence.",
  "Spend five minutes stretching your neck, shoulders, and back.",
  "List your top three priorities for today on paper.",
  "Take a cold rinse for 30 seconds at the end of a shower.",
  "Clean your desk before starting your next task.",
  "Stand outside for two minutes and get natural light.",
  "Read one saved note with your long-term goals.",
  "Send one message to reconnect with someone who supports your growth.",
  "Do ten slow deep breaths before opening social media.",
  "Put your phone in another room for 30 minutes.",
  "Write one sentence that reframes a current problem as a challenge.",
  "Complete one small task you have been postponing.",
  "Drink water before your next coffee.",
  "Do a 10-minute walk without headphones.",
  "Unsubscribe from one email list that drains your attention.",
  "Add one healthy item to your next meal.",
  "Review your spending from the last 24 hours.",
  "Set tomorrow's outfit or work setup tonight.",
  "Do 60 seconds of plank to practice discomfort tolerance.",
  "Write one boundary you will keep today.",
  "Read one paragraph out loud to improve focus.",
  "Clear 10 old photos or files from your phone.",
  "Choose one habit trigger and write an if-then plan for it.",
  "Pause for one minute before responding to a stressful message.",
  "Do five push-ups every time you feel like procrastinating.",
  "Prepare a glass or bottle of water for the morning.",
  "Spend 15 minutes organizing a single drawer or shelf.",
  "Write down one fear and one action that counters it.",
  "Practice two minutes of box breathing.",
  "Switch one sugary drink for water or tea.",
  "Do one kind act without telling anyone.",
  "Review your calendar and remove one non-essential commitment.",
  "Read your notes from the last week and highlight one win.",
  "Take a 5-minute break to reset your posture and eyes.",
  "Set a bedtime alarm 30 minutes earlier than usual.",
  "Write one sentence of self-forgiveness and one next step.",
  "Do one task in complete single-task mode with no tab switching.",
  "Put one visible reminder of your goal on your desk.",
  "Spend 10 minutes learning one practical skill.",
  "Say no to one impulse purchase today.",
  "Tidy your bag or backpack and remove what you do not need.",
  "Track your mood in one word at three points today.",
  "End the day by writing one promise for tomorrow.",
  "Write one line about what made you proud today.",
];

export function pickRedemptionMessage(dayNumber) {
  const dayIdx = Math.max(0, dayNumber - 1);
  const quote = REDEMPTION_QUOTES[dayIdx % REDEMPTION_QUOTES.length];
  const action = REDEMPTION_MICRO_ACTIONS[dayIdx % REDEMPTION_MICRO_ACTIONS.length];
  return { quote, action };
}
